services:
  # Combined Frontend + Backend Fullstack Service
  - type: web
    name: miniminds-fullstack
    env: docker
    plan: starter
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: VITE_API_URL
        value: https://miniminds-fullstack.onrender.com/api
      - key: DATABASE_URL
        fromDatabase:
          name: miniminds-db
          property: connectionString
      - key: DIRECT_URL
        fromDatabase:
          name: miniminds-db
          property: connectionString
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_PUBLISHABLE_KEY
        sync: false
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_WEBHOOK_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /api/health

# Database
databases:
  - name: miniminds-db
    databaseName: miniminds
    user: miniminds_user
    plan: starter
    region: oregon
